### PR TITLE
Moved window controls to window-control.css and start using it in gtk.css

### PR DESCRIPTION
**Pull request by Defman21**

### CODE REVIEW

**Comment by Defman21** [comment]
It's better to merge that because storing window controls styles not in window-control.css when you have the file window-control.css is a bit strange. Also it would be easier to change window controls in the future.

**Comment by crutchcorn** [comment]
SO TRUE!

**Comment by crutchcorn** [comment]
I think we should parse most of the stuff!

**Comment by crutchcorn** [comment]
Damn you, I was JUST working on this. ROFL

**Comment by Defman21** [comment]
> Damn you, I was JUST working on this. ROFL

I'm reading your mind, bro :smile:

**Comment by crutchcorn** [comment]
> I'm reading your mind, bro :smile: 

You so are!

**Pull request merged**
