### PR TITLE
Fixed #5

### LINKED ISSUE #5: Menus not readable
screenshot from 2015-04-17 12 24 07
screenshot from 2015-04-17 12 23 12

The first picture is from Elementary OS theme the latter from xgtk, in the latter, menus are very ugly and the text is hardly readable. 
In my opinion, copying the elementary theme would be the best thing, since that it's colours are consistent with xgtk ones (and of course with yosemite ones too).
There are also those bad blue highlights...

### PR DESCRIPTION
**Pull request by Defman21**

### CODE REVIEW

**Comment by crutchcorn** [comment]
Can you upload a screen shot, I am still having the issue

**Comment by crutchcorn** [comment]
Is this on top of the changes you made or just by itself?

**Comment by Defman21** [comment]
By myself. Try to kill wingpanel. <s>If the fix still doesn't work - try to inspect a popup with Ctrl+Shift+I and gtk3 dev.</s>

**Comment by crutchcorn** [comment]
Well, it now makes all popups the same.. That's a plus... Kinda.... But now they're all the broken kind

**Comment by Defman21** [comment]
> But now they're all the broken kind

What?

**Comment by crutchcorn** [comment]
> What?

They all look like

**Comment by Defman21** [comment]
Look like what? I don't see any screen if you attached it.

**Comment by Defman21** [comment]
Ahh, I see the screen now...

**Comment by crutchcorn** [comment]
Wait... Nevermind. That was my fault

**Comment by Defman21** [comment]
Fine.

**Comment by crutchcorn** [comment]
Sorry mate!

**Comment by Defman21** [comment]
No worries! Thank you for merging it.

**Pull request merged**
